// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXujEQYqilDlQan-jVveKTZhcIZccwjKs',
    appId: '1:492905621777:android:7b085b06279b14e85404b0',
    messagingSenderId: '492905621777',
    projectId: 'chat-app-513bb',
    storageBucket: 'chat-app-513bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlUFYbsrUDEiwgDgG6oE3PnBDJsQOC8Q',
    appId: '1:492905621777:ios:3ce4c0ca5896471a5404b0',
    messagingSenderId: '492905621777',
    projectId: 'chat-app-513bb',
    storageBucket: 'chat-app-513bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOlUFYbsrUDEiwgDgG6oE3PnBDJsQOC8Q',
    appId: '1:492905621777:ios:3ce4c0ca5896471a5404b0',
    messagingSenderId: '492905621777',
    projectId: 'chat-app-513bb',
    storageBucket: 'chat-app-513bb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}